# Generated by Django 4.2.7 on 2025-10-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0003_delete_employeesession"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("pending_rest", "Aguardando Interjornada"),
                            ("blocked", "Bloqueado"),
                            ("completed", "Concluído"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("first_access", models.DateTimeField(verbose_name="Primeiro Acesso")),
                (
                    "last_access",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Acesso"
                    ),
                ),
                (
                    "block_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Início do Bloqueio"
                    ),
                ),
                (
                    "return_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Horário de Retorno"
                    ),
                ),
                (
                    "work_duration_minutes",
                    models.IntegerField(verbose_name="Duração de Trabalho (min)"),
                ),
                (
                    "rest_duration_minutes",
                    models.IntegerField(verbose_name="Duração de Interjornada (min)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="employees.employee",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Funcionário",
                "verbose_name_plural": "Sessões de Funcionários",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "state"],
                        name="employee_se_employe_4b7c43_idx",
                    ),
                    models.Index(fields=["state"], name="employee_se_state_1ee8ad_idx"),
                    models.Index(
                        fields=["first_access"], name="employee_se_first_a_551598_idx"
                    ),
                    models.Index(
                        fields=["return_time"], name="employee_se_return__b3abe0_idx"
                    ),
                ],
            },
        ),
    ]
