# Generated by Django 4.2.7 on 2025-10-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeesession",
            name="pending_rest_since",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Pendente de Interjornada Desde"
            ),
        ),
    ]
