# Generated by Django 4.2.7 on 2025-10-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_sessions", "0002_add_pending_rest_since"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeesession",
            name="pending_rest_since",
        ),
        migrations.AlterField(
            model_name="employeesession",
            name="created_at",
            field=models.DateTimeField(verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="employeesession",
            name="updated_at",
            field=models.DateTimeField(verbose_name="Atualizado em"),
        ),
    ]
