# Generated by Django 4.2.7 on 2025-10-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_sessions",
            "0003_remove_employeesession_pending_rest_since_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeesession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="employeesession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
