# Generated by Django 4.2.7 on 2025-10-09 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterjornadaRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Regra"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "work_duration_minutes",
                    models.IntegerField(verbose_name="Duração de Trabalho (min)"),
                ),
                (
                    "rest_duration_minutes",
                    models.IntegerField(verbose_name="Duração de Interjornada (min)"),
                ),
                (
                    "apply_to_all",
                    models.BooleanField(default=False, verbose_name="Aplicar a Todos"),
                ),
                (
                    "employee_groups",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Grupos de Funcionários"
                    ),
                ),
                (
                    "exempt_employee_groups",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Grupos Isentos"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de Início"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de Fim"
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Dias da Semana"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de Interjornada",
                "verbose_name_plural": "Regras de Interjornada",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InterjornadaCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("work", "Trabalho"),
                            ("rest", "Interjornada"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="work",
                        max_length=20,
                        verbose_name="Estado Atual",
                    ),
                ),
                ("cycle_start", models.DateTimeField(verbose_name="Início do Ciclo")),
                ("work_start", models.DateTimeField(verbose_name="Início do Trabalho")),
                (
                    "work_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim do Trabalho"
                    ),
                ),
                (
                    "rest_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Início da Interjornada"
                    ),
                ),
                (
                    "rest_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim da Interjornada"
                    ),
                ),
                (
                    "actual_work_duration_minutes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Duração Real de Trabalho (min)",
                    ),
                ),
                (
                    "actual_rest_duration_minutes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Duração Real de Interjornada (min)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="employees.employee",
                        verbose_name="Funcionário",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="interjornada.interjornadarule",
                        verbose_name="Regra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo de Interjornada",
                "verbose_name_plural": "Ciclos de Interjornada",
                "ordering": ["-cycle_start"],
            },
        ),
        migrations.CreateModel(
            name="InterjornadaViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("early_access", "Acesso Antecipado"),
                            ("late_access", "Acesso Tardio"),
                            ("exceeded_work_time", "Tempo de Trabalho Excedido"),
                            ("insufficient_rest", "Interjornada Insuficiente"),
                            ("unauthorized_access", "Acesso Não Autorizado"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Violação",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Severidade",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Detalhes"),
                ),
                (
                    "violation_time",
                    models.DateTimeField(verbose_name="Horário da Violação"),
                ),
                (
                    "detected_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Horário de Detecção"
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(blank=True, null=True, verbose_name="Ação Tomada"),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="Resolvida"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolvida em"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="interjornada.interjornadacycle",
                        verbose_name="Ciclo",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolvida por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Violação de Interjornada",
                "verbose_name_plural": "Violações de Interjornada",
                "ordering": ["-violation_time"],
                "indexes": [
                    models.Index(
                        fields=["violation_type"], name="interjornad_violati_35b88a_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="interjornad_severit_9d03c5_idx"
                    ),
                    models.Index(
                        fields=["violation_time"], name="interjornad_violati_e2c50b_idx"
                    ),
                    models.Index(
                        fields=["resolved"], name="interjornad_resolve_7138b3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InterjornadaStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "total_cycles",
                    models.IntegerField(default=0, verbose_name="Total de Ciclos"),
                ),
                (
                    "completed_cycles",
                    models.IntegerField(default=0, verbose_name="Ciclos Concluídos"),
                ),
                (
                    "cancelled_cycles",
                    models.IntegerField(default=0, verbose_name="Ciclos Cancelados"),
                ),
                (
                    "total_work_time_minutes",
                    models.IntegerField(
                        default=0, verbose_name="Tempo Total de Trabalho (min)"
                    ),
                ),
                (
                    "total_rest_time_minutes",
                    models.IntegerField(
                        default=0, verbose_name="Tempo Total de Interjornada (min)"
                    ),
                ),
                (
                    "average_work_time_minutes",
                    models.FloatField(
                        default=0, verbose_name="Tempo Médio de Trabalho (min)"
                    ),
                ),
                (
                    "average_rest_time_minutes",
                    models.FloatField(
                        default=0, verbose_name="Tempo Médio de Interjornada (min)"
                    ),
                ),
                (
                    "total_violations",
                    models.IntegerField(default=0, verbose_name="Total de Violações"),
                ),
                (
                    "resolved_violations",
                    models.IntegerField(default=0, verbose_name="Violações Resolvidas"),
                ),
                (
                    "critical_violations",
                    models.IntegerField(default=0, verbose_name="Violações Críticas"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interjornada_stats",
                        to="employees.employee",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estatística de Interjornada",
                "verbose_name_plural": "Estatísticas de Interjornada",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="interjornad_employe_1d6505_idx",
                    ),
                    models.Index(fields=["date"], name="interjornad_date_393ae1_idx"),
                ],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="interjornadacycle",
            index=models.Index(
                fields=["employee", "current_state"],
                name="interjornad_employe_522d68_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interjornadacycle",
            index=models.Index(
                fields=["current_state"], name="interjornad_current_19fd7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interjornadacycle",
            index=models.Index(
                fields=["cycle_start"], name="interjornad_cycle_s_51561e_idx"
            ),
        ),
    ]
