# Generated by Django 4.2.7 on 2025-10-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="session_processed",
            field=models.BooleanField(
                default=False, verbose_name="Processado para Sessão"
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="session_processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Processado para Sessão em"
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="session_processing_error",
            field=models.TextField(
                blank=True, null=True, verbose_name="Erro no Processamento de Sessão"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["session_processed"], name="logs_access_session_fc34c1_idx"
            ),
        ),
    ]
