# Generated by Django 4.2.7 on 2025-10-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_accesslog_session_processed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="created_at",
            field=models.DateTimeField(verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="updated_at",
            field=models.DateTimeField(verbose_name="Atualizado em"),
        ),
    ]
