# Generated by Django 4.2.7 on 2025-10-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0003_alter_accesslog_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="event_type",
            field=models.IntegerField(
                choices=[
                    (1, "Entrada"),
                    (2, "Saída"),
                    (3, "Não Identificado"),
                    (4, "Erro de Leitura"),
                    (5, "Timeout"),
                    (6, "Acesso Negado"),
                    (7, "Acesso Autorizado"),
                    (8, "Acesso Bloqueado"),
                    (13, "Desistência"),
                ],
                verbose_name="Tipo de Evento",
            ),
        ),
    ]
