# Generated by Django 4.2.7 on 2025-10-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_add_is_manual_field"),
        ("logs", "0004_alter_accesslog_event_type"),
    ]

    operations = []
