# Generated by Django 4.2.7 on 2025-10-09 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.IntegerField(unique=True, verbose_name="ID do Dispositivo"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "employee_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Código do Funcionário",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_exempt",
                    models.BooleanField(
                        default=False, verbose_name="Isento de Interjornada"
                    ),
                ),
                (
                    "groups",
                    models.JSONField(blank=True, default=list, verbose_name="Grupos"),
                ),
                (
                    "exemption_groups",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Grupos de Isenção"
                    ),
                ),
                (
                    "work_duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duração de Trabalho (min)"
                    ),
                ),
                (
                    "rest_duration_minutes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Duração de Interjornada (min)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Grupo"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "is_exemption_group",
                    models.BooleanField(default=False, verbose_name="Grupo de Isenção"),
                ),
                (
                    "work_duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duração de Trabalho (min)"
                    ),
                ),
                (
                    "rest_duration_minutes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Duração de Interjornada (min)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Grupo de Funcionários",
                "verbose_name_plural": "Grupos de Funcionários",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("pending_rest", "Aguardando Interjornada"),
                            ("blocked", "Bloqueado"),
                            ("completed", "Concluído"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("first_access", models.DateTimeField(verbose_name="Primeiro Acesso")),
                (
                    "last_access",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Acesso"
                    ),
                ),
                (
                    "block_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Início do Bloqueio"
                    ),
                ),
                (
                    "return_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Horário de Retorno"
                    ),
                ),
                (
                    "work_duration_minutes",
                    models.IntegerField(verbose_name="Duração de Trabalho (min)"),
                ),
                (
                    "rest_duration_minutes",
                    models.IntegerField(verbose_name="Duração de Interjornada (min)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="employees.employee",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão de Funcionário",
                "verbose_name_plural": "Sessões de Funcionários",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "state"],
                        name="employees_e_employe_8eb3eb_idx",
                    ),
                    models.Index(fields=["state"], name="employees_e_state_076e0d_idx"),
                    models.Index(
                        fields=["first_access"], name="employees_e_first_a_5f88cc_idx"
                    ),
                    models.Index(
                        fields=["return_time"], name="employees_e_return__8a6f02_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["device_id"], name="employees_e_device__e1b671_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_code"], name="employees_e_employe_f8cfea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["is_active"], name="employees_e_is_acti_ff761b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["is_exempt"], name="employees_e_is_exem_9dea95_idx"
            ),
        ),
    ]
