# Generated by Django 4.2.7 on 2025-10-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeegroup",
            name="device_group_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="ID do Grupo no Dispositivo",
            ),
        ),
    ]
