# Generated by Django 4.2.7 on 2025-10-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employeegroup_device_group_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeSession",
        ),
    ]
