# Generated by Django 4.2.7 on 2025-10-14 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_delete_employeesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.employeegroup",
                verbose_name="Grupo Atual",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="original_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_employees",
                to="employees.employeegroup",
                verbose_name="Grupo Original",
            ),
        ),
        migrations.AddField(
            model_name="employeegroup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="employeegroup",
            name="is_blacklist",
            field=models.BooleanField(default=False, verbose_name="Grupo de Blacklist"),
        ),
    ]
