# Generated by Django 4.2.7 on 2025-10-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employee_group_employee_original_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="alert_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Padrão"),
                    ("rh", "RH"),
                    ("supervisor", "Supervisor"),
                    ("coordenador", "Coordenador"),
                    ("ti", "TI"),
                ],
                default="",
                max_length=20,
                verbose_name="Tipo de Aviso",
            ),
        ),
    ]
